name: flutter_screen_recording_platform_interface
description: A common platform interface for the flutter_screen_recording plugin
version: 1.0.0
homepage: "https://github.com/Isvisoft/flutter_screen_recording/tree/web/flutter_screen_recording_platform_interface"
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  meta: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
